### ISSUE TITLE
Gesture problems with UITableView

### ISSUE THREAD

**Issue by vleango** [romaonthego/REFrostedViewController#59]
When panGesture is enabled, the top controller (has a tableView inside) doesn't scroll up and down properly on same cells (pretty random cells). When this occurs, the menu's pan gesture is triggered instead.

I have also noticed this problem when the Left Menu has a table view.

I have been trying to get it to work for both gestures, but not successful so far.

**Comment by CianApple** [comment]
I had this issue as well. But I have a very simple implementation for this issue. The logic used by me in DemoNavigationController:

Instead of:
[self.view addGestureRecognizer:[[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(panGestureRecognized:)]];

Use:
UIView *vw_pan = [[UIView alloc] initWithFrame:CGRectMake(0, self.navigationBar.frame.size.height + [UIApplication sharedApplication].statusBarFrame.size.height, 40, self.view.frame.size.height)];
vw_pan.backgroundColor = [UIColor clearColor];
[self.view addSubview:vw_pan];
[vw_pan addGestureRecognizer:[[UIPanGestureRecognizer alloc] initWithTarget:self action:@selector(panGestureRecognized:)]];

This means decrease the pangesture from full screen to a limited area in the left edge of the screen. Hope it helps.
